name: Flutter CI Workflow

on:
  push:
    branches:
      - cybersecurity
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.3'  

    - name: Install dependencies
      run: flutter pub get

    - name: Run Flutter Analyzer (Static Code Analysis)
      run: flutter analyze

    - name: Run Flutter Tests
      run: flutter test

    - name: Run Linter
      run: flutter pub run lint

    - name: Build APK (if needed)
      run: flutter build apk --release

    - name: Archive APK (optional)
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: app-release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
